#!/bin/sh

fancy_echo "------- Setting Up Applications, dependencies, and dotfiles -------"

fancy_echo "------- Some dependencies not managed with laptop -----------------"
fancy_echo " * Sound Siphon"

# homebrew installations
brew bundle --file=- <<EOF
  cask "1password"
  cask "acslogo"
  cask "adventure"
  cask "encryptme"
  cask "encryptr"
  cask "google-chrome"
  cask "imageoptim"
  cask "iterm2"
  cask "keybase"
  cask "ngrok"
  cask "rescuetime"
  cask "semaphor"
  cask "spotify"
  cask "todotxt"
  cask "veracrypt"
  cask "zwift"

  # scanner
  tap "homebrew/cask-drivers"
  cask "fujitsu-scansnap-manager-s1300"

  # fonts
  tap "caskroom/fonts"
  cask "font-fira-code"
  cask "font-source-code-pro"

  # for dotfiles
  tap "thoughtbot/formulae"
  brew "rcm"

  brew "mas" # Apple App Store integration

  brew "hugo"
  brew "jq"

  brew "go"
  brew "terraform"
  brew "awscli"
  brew "graphviz"

  cask "docker"

  brew "ttygif"
  brew "imageoptim-cli"

  brew "youtube-dl"

  brew "zork"

EOF

# install asdf managed libraries

install_asdf_plugin "elixir" "https://github.com/asdf-vm/asdf-elixir.git"

# install Apps From App Store
mas install 568494494 # Pocket
mas install 1225570693 # Ulysses
mas install 1055511498 # Day One
mas install 1142578753 # Omnigraffle 7
mas install 803453959 # slack
mas install 454948164 #TaskBadges

# upgrade existing apps
mas upgrade

# gems
gem_install_or_update "middleman"
gem_install_or_update "middleman-blog"
gem_install_or_update "pry"

# bring in or pull from Thoughtbot's dotfiles
if [ ! -d "$HOME/dotfiles" ]; then
  git clone git://github.com/thoughtbot/dotfiles.git ~/dotfiles
else
  git -C ~/dotfiles pull origin master
fi

# source dotfiles
env RCRC=$HOME/dotfiles/rcrc rcup

